version: '3'

services:
  app1:
    build: ./
    ports:
      - "3000"
  app2:
    build: ./
    ports:
      - "3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
